name: InfinityFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Infinity Freedom server apart of barkdog network.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza xBarkPuppy1]

# plugin.yml is no longer used to define commands.
